//Adding 3 records into Products
INSERT INTO Products Values (1, 'DELL Laptop',599.99);
INSERT INTO Products Values (2, 'HP Printer',129.59);
INSERT INTO Products Values (3, 'Powerbank', 29.99);

//Adding 3 records into Customers
INSERT INTO Customers Values (1, 'John','Collins',11122223333);
INSERT INTO Customers Values (2, 'Tracey','Schwartz',00022291921);
INSERT INTO Customers Values (3, 'Angelo','Gibbs',99928281928);

//Adding 3 records into Orders
INSERT INTO Orders Values(1,1,1)
INSERT INTO Orders Values(2,2,2)
INSERT INTO Orders Values(3,3,3)

//Add iPhone into Product Priced at $200
INSERT INTO Products Values (4,'iPhone',200.00);

//Add Tina Smith into Customers
INSERT INTO Customers Values (4,'Tina','Smith',99827128321);

//Creat Order for Tina Smith bought an iPhone
INSERT INTO Orders Values (4,4,4);

//Report all orders by Tina Smith
SELECT * FROM Orders WHERE CustomerID IN (SELECT ID FROM Customers WHERE FirstName = 'Tina' AND Lastname = 'Smith');

//Report all revenue generated by sales of iPhone
SELECT p.ID,p.Name,SUM(Price) FROM Products p INNER JOIN Orders o ON p.ID = o.ProductID WHERE p.Name = 'iPhone' GROUP BY p.Name;

//Increase the price of iPhone to $250
UPDATE Products SET Price=250 WHERE Name = 'iPhone';
